services:
  nest-backend:
    container_name: nest-app
    image: nest-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 4500:${PORT}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GEN_SALT=${GEN_SALT}
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - APP_NAME=${APP_NAME}
      - PORT=${PORT}
      - BACKEND_URL=${BACKEND_URL}
      - MAIL_TRAP_HOST=${MAIL_TRAP_HOST}
      - MAIL_TRAP_PORT=${MAIL_TRAP_PORT}
      - MAIL_TRAP_USERNAME=${MAIL_TRAP_USERNAME}
      - MAIL_TRAP_PASSWORD=${MAIL_TRAP_PASSWORD}
      - NODE_ENV=${NODE_ENV}
    networks:
      - backend_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - postgres-test

  postgres:
    container_name: postgres-db
    image: postgres:12
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wallet
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-test:
    container_name: postgres-db-test
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wallet_test
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - backend_network
    ports:
      - '5050:80'
    depends_on:
      - postgres

  redis:
    container_name: redis-db
    image: redis
    environment:
      - REDIS_PORT=6379
    ports:
      - 6379:6379
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - redis:/data

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: {}
  postgres_data_test: {}
  redis:
    driver: local
